---
- name: Deploy Ansible User
  hosts: all
  tasks:
  - name: Create User
    user:
      name: devops
      groups: "{{ admin_group }}"
      comment: 'Ansible Management Account'
      expires: -1
      password: '%f8d03kljfe#fjslknfsk'

  - name: Install SSH Key
    authorized_key:
      user: devops
      state: present
      managed_dir: true
      key: "{{ lookup('file', '/home/bob/.ssh/id_rsa.pub') }}"

  - name: Setup Devops Sudo Access
    copy: 
      dest: /etc/sudoers.d/devops
      content: 'devops ALL=(ALL) NOPASSWD: ALL'
      validate: /usr/sbin/visudo -cf %s
  





*********************************************************************

#ansible inventory INI file

[redhat]
192.168.112.[4:5]

[redhat:vars]
admin_group=wheel

[ubuntu]
192.168.112.6

[ubuntu:vars]
admin_group=sudo